Fix Rubocop cop deprecation failure
Builds are failing due to the following Rubocop error.
```
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
```